name: Build macOS Package and Release

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --target-architecture universal2 main.py

      - name: Create ZIP of built app
        run: |
          cd dist
          zip -r main-macos.zip ./*

      - name: Create macOS Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: macos-v0.1.2.${{ github.run_number }}
          name: macOS Release v0.1.2.${{ github.run_number }}
          files: dist/main-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

