name: Build, Package and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name:  Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller main.spec

      - name: Install Inno Setup
        run: |
          choco install innosetup --yes

      - name: Run Inno Setup Compiler
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer/installer.iss" "/DMyOutputDir=$env:GITHUB_WORKSPACE\dist\main"

      - name: List Output Files
        run: dir installer/Output

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: win-v0.1.2.${{ github.run_number }}
          name: Windows Release v0.1.2.${{ github.run_number }}
          files: installer/Output/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}